# Generated by Django 4.2.3 on 2023-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkcategory_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url', models.URLField(max_length=50, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=50, verbose_name='عنوان لینک')),
                ('description', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='عکس اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات اسلایدر',
                'verbose_name_plural': ' تنظیمات اسلایدرها',
            },
        ),
    ]
