# Generated by Django 4.2.3 on 2023-08-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'verbose_name': 'بنر تبلیغاتی', 'verbose_name_plural': 'بنرهای تبلیغاتی'},
        ),
    ]
